### ISSUE TITLE
Game.stop fails if not passed a callback

### ISSUE THREAD

**Issue by heneryville** [dominicbarnes/node-minecraft-runner#3]
Game.stop will die if not passed a callback. The existance of the callback should be tested before calling it.

I was going to submit a pull request myself, but the unit tests aren't working on my machine. The game.start tests timeout on my machine.

**Comment by dominicbarnes** [comment]
Yeah, the time it takes to start up a minecraft server can vary wildly between machines. I will work on adding a more easily configurable way to extend this timeout.

In the meantime, a simple `function () {}` will have to do. I'll keep you posted on a fix. (in fact, I'll skim around and apply this same fix all around)

Thanks for taking the time to submit this! :)

**Comment by dominicbarnes** [comment]
Fixed with version 0.0.5
