### ISSUE TITLE
Players array is not updated

### ISSUE THREAD

**Issue by heneryville** [dominicbarnes/node-minecraft-runner#5]
There is a players array in the code, but it appears to never be updated when players join or leave.

**Comment by dominicbarnes** [comment]
Yeah, I used to have that feature in there. I was planning on deprecating that in favor of just using the `/list` command. This should definitely be cleaned up.

**Comment by dominicbarnes** [comment]
As it turns out, `lib/patterns.js` actually contains the code that updates the `players` array. Ignore the commit that shows me removing the array, I re-added them in a later commit.
